### PR TITLE
Highscore

### PR DESCRIPTION
**Pull request by stefvanhouten**

### CODE REVIEW

**Comment by stefvanhouten** [comment]
Code looks fine except for when WriteToFile is called without overwrite. This code will not work since the StreamWriter is expecting a string but recieves a byte array.

**Comment by SDanDyS** [comment]
Pushed a new version with bug fix and tested with and without overwrite rule set.
ATTENTION:
Second dev confirmation required on the subject
REASON:
When tested WITH overwrite set to true, it resulted in the desired outcome, however when overwrite was set to false, it kept the highscores very well together without duplicating information (like the first time when we used the FILES class).

-> A developer has either created a fix for this (in another file) which i'm unaware of, or something is going wrong and this could be very well undesired behavior and should be inspected.

REQUEST: Prior to MERGING, I would like to be confirmed that the behavior is expected. Please provide arguments as to WHY, rather then just stating it's desired behavior.

**Comment by stefvanhouten** [comment]
To me this seems like expected behaviour;

In the current version we never want to append data to the file, we always want to overwrite the contents. 
When the game is launched we load all data from the highscores save file into the highscores class and store this in the propertie Highscores which is a list. Whenever new highscores are added, in the current state it is also instantly written to the file, this is done with overwrite: true. 

if we were to use overwrite: false it is expected to have duplicate data, this because the current implementation is not ideal. To fix this behaviour we simply need to change when our data is written to the highscores save file (which is when the application gets closed, this will increase performance and prevent accessing the save files while we are playing the game).

**Comment by SDanDyS** [comment]
"if we were to use overwrite: false it is expected to have duplicate data" - Stef van Houten

The unpredicted behavior is: It does NOT create duplicate data anymore. Either a developer changed something I am not aware of, or this is something we'll have to inspect closer.
Expected behavior would've been duplicate data, but somehow this is not happening... and I cannot find out as to why this is happening.

**Review by SDanDyS — APPROVED** [review]
Besides the fact that the overwrite false didn't do the job, the code works and looks good to me.

**Pull request closed without merging**
